/**
 * All constant to be used by actions and reducers
 */
export const TVSHOWSLIST_FETCHING = 'TVSHOWSLIST_FETCHING';
export const TVSHOWSLIST_FETCH_ERROR = 'TVSHOWSLIST_FETCH_ERROR';
export const TVSHOWSLIST_FETCH_SUCCESS = 'TVSHOWSLIST_FETCH_SUCCESS';

export const TVSHOW_INFORMATION_FETCHING = 'TVSHOW_INFORMATION_FETCHING';
export const TVSHOW_INFORMATION_FETCH_ERROR = 'TVSHOW_INFORMATION_FETCH_ERROR';
export const TVSHOW_INFORMATION_FETCH_SUCCESS = 'TVSHOW_INFORMATION_FETCH_SUCCESS';

export const RELATED_TVSHOWS_INFORMATION_FETCHING = 'RELATED_TVSHOWS_INFORMATION_FETCHING';
export const RELATED_TVSHOWS_INFORMATION_FETCH_ERROR = 'RELATED_TVSHOWS_INFORMATION_FETCH_ERROR';
export const RELATED_TVSHOWS_INFORMATION_FETCH_SUCCESS = 'RELATED_TVSHOWS_INFORMATION_FETCH_SUCCESS';
